### ISSUE TITLE
TODO: document production server setup

### ISSUE THREAD

**Issue by ehanahamed** [ehanahamed/quizfreely#10]
- [x] document setting up quizfreely web
  - [x] git sparse checkout
  - [x] copying .env & quizfreely-web.service
  - [x] running with systemd service
  - [x] configuring .env
  - [x] configuring systemd service
- [x] document setting up api & db+auth
- [x] document setting up caddy
  - [x] caddyfile
  - [x] installation
  - [x] digialocean dns in caddyfile
  - [x] systemd service file
- [x] document installing dependencies/packages/thingies
  - [x] nodejs

**Comment by ehanahamed** [comment]
This is mostly done, docs/dev/api/auth.md needs to be finished
