### ISSUE TITLE
TODO: finish developing auth stuff for our own api & db+auth

### ISSUE THREAD

**Issue by ehanahamed** [ehanahamed/quizfreely#11]
Right now, ~~we are~~ (I am) making quizfreely's "custom" auth & db api (with postgres and fastify) (source code is under `api/` in this repo) So list of thingies to do for auth (user accounts & login & sessions & etc) goes here!

To-do:
- [x] username & password auth
  - [x] sign up/create account
    - [x] insert into postgres `auth.users`
      - [x] secure password hashing with salt
      - [x] set default `display_name`
    - [x] api/server-side username & password validation
    - [x] readable & useful response body json
      - [x] readable response json for errors
      - [x] specific error codes/status from username & password validation
      - [x] usable data response json on successful sign up
        - [x] with session token? cookie?
  - [x] sign in
    - [x] verify imputed password with encrypted password
    - [x] useful response in body json
      - [x] readable response json for errors
      - [x] usable data response json on successful log in
        - [x] with session token? cookie?
    - [x] insert or update postgres `auth.sessions`
- [x] sessions
  - [x] auth.sessions table
  - [x] write new session to auth.sessions on signup or signin and return session token
  - [x] store session token in cookie
  - [x] session expiry
- [x] auth validation/verification
  - [x] check session token from cookies to give access to certain actions in the api

**Comment by ehanahamed** [comment]
Done!
